# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.menu_builder:
        class: AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory", @doctrine, @request_stack]

    app.app_utils:
        class: AppBundle\Utils\ShiftLogUtils
        arguments: [@doctrine.orm.entity_manager]

    app.comparison_utils:
        class: AppBundle\Utils\ComparisonUtils
        arguments: [@doctrine]

    app.wx_utils:
        class: AppBundle\Utils\WXUtils

    app.geo_utils:
        class: AppBundle\Utils\GeoUtils

    app.ofp_utils:
        class: AppBundle\Utils\OFPUtils

    app.fw_utils:
        class: AppBundle\Utils\FWUtils
        arguments: [@doctrine, @app.wx_utils, @form.factory, @router, @knp_snappy.pdf]

    app.main_menu:
            class: Knp\Menu\MenuItem
            factory_service: app.menu_builder
            factory_method: createMainMenu
            arguments: ["@security.context"]
            tags:
                - { name: knp_menu.menu, alias: main }

    app.comparison_menu:
            class: Knp\Menu\MenuItem
            factory_service: app.menu_builder
            factory_method: createComparisonMenu
            arguments: []
            tags:
                - { name: knp_menu.menu, alias: comparison_menu }

    app.flightwatch_listener:
      class: AppBundle\Listener\FlightWatchListener
      tags:
        - { name : doctrine.event_listener, event : preUpdate }

    app.twig_extension:
      class: AppBundle\Twig\AppExtension
      public: false
      tags:
        - { name: twig.extension }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
