<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * FlightwatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightwatchRepository extends EntityRepository
{
    public function findByDeskWithInfo($desk, $dp = NULL) {

        $qb = $this->createQueryBuilder('f');

        $qb
            ->addSelect('i')
            ->join('f.info', 'i')
            ->where('f.completed is null')
            ->andWhere('i.pointName not like :pointName')
            ->setParameter('pointName', 'EXP%');

        if($desk != 'all'){
            $qb
                ->andWhere('f.desk = :desk')
                ->setParameter('desk', $desk);
        }

        if($dp){
            $qb
                ->andWhere('f.erd IS NOT NULL');
        }

        $qb
            ->orderBy('f.flightDate', 'ASC')
            ->addOrderBy('f.std', 'ASC');

        return $qb
            ->getQuery()
            ->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)
            ->getArrayResult();

        /*return $this->createQueryBuilder('f')
            ->addSelect('i')
            ->join('f.info', 'i')
            ->where('f.completed is null')
            ->andWhere('i.pointName not like :pointName')
            ->andWhere('f.desk = :desk')
            ->setParameter('desk', $desk)
            ->setParameter('pointName', 'EXP%')
            ->orderBy('f.flightDate', 'ASC')
            ->addOrderBy('f.std', 'ASC')
            ->getQuery()
            ->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)
            ->getArrayResult();*/

    }

    public function findAllWithInfo() {

        return $this->createQueryBuilder('f')
            ->addSelect('i')
            ->join('f.info', 'i')
            ->where('f.completed is null')
            ->andWhere('i.pointName not like :pointName')
            ->setParameter('pointName', 'EXP%')
            ->orderBy('f.flightDate', 'ASC')
            ->addOrderBy('f.std', 'ASC')
            ->getQuery()
            ->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)
            ->getArrayResult();

    }

    //TODO : Fix, this is ugly.
    public function findCompletedByDate($date){

        return $this->createQueryBuilder('f')
            ->addSelect('i')
            ->join('f.info', 'i')
            ->where('f.completed = 1')
            ->andWhere('f.flightDate = :date')
            ->setParameter('date', $date)
            ->getQuery()
            ->setHint(Query::HINT_INCLUDE_META_COLUMNS, true)
            ->getArrayResult();

    }
}
