<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShiftLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftLogRepository extends EntityRepository
{
    public function findAllCurrent()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
            ->from('AppBundle:ShiftLog', 's')
            ->orderBy('s.sequence', 'ASC');

        return $qb->getQuery()->getArrayResult();
    }

    public function findCurrentByType($type = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
            ->from('AppBundle:ShiftLog', 's')
            ->where('s.infoType = ?1')
            ->setParameter(1, $type);

        return $qb->getQuery()->getSingleResult();
    }


}
