<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShiftLogArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftLogArchiveRepository extends EntityRepository
{
    public function checkExistsShiftReport($archivedDate, $archivedShift)
    {
        $em = $this->findBy(array(
            'archivedDate' => $archivedDate,
            'archivedShift' => $archivedShift));

        if(count($em) > 0){
            return TRUE;
        }else{
            return FALSE;
        }
    }
}
