<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShiftLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftLogRepository extends EntityRepository
{
    public function findCurrentByType($type = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
            ->from('AppBundle:ShiftLog', 's')
            ->where('s.infoType = ?1')
            ->setParameter(1, $type);

        return $qb->getQuery()->getSingleResult();
    }

    public function returnAllOrdered()
    {
        $info_result = [];
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
            ->from('AppBundle:ShiftLog', 's')
            ->orderBy('s.sequence', 'ASC');

        $entities = $qb->getQuery()->getArrayResult();

        foreach ($entities as $entity) {
            $info_result[] = array('content' => $entity['content'],
                'info_header' => $entity['infoHeader'],
                'info_type' => $entity['infoType'], );
        }

        return $info_result;
    }
}
