<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShiftLogArchiveRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftLogArchiveRepository extends EntityRepository
{
    public function checkExistsShiftReport($archivedDate, $archivedShift)
    {
        $em = $this->findBy(array(
            'archivedDate' => $archivedDate,
            'archivedShift' => $archivedShift, ));

        if (count($em) > 0) {
            return true;
        } else {
            return false;
        }
    }

    public function moveActiveToArchive($user, $shift, $date)
    {
        $em = $this->getEntityManager();

        $entities = $em->getRepository('AppBundle:ShiftLog')->returnAllOrdered();

        foreach ($entities as $entity) {
            $shiftLogArchive = new ShiftLogArchive();
            $shiftLogArchive->insertArchive($entity['content'], $entity['info_type'], $entity['info_header'],
                $user, $shift, $date);
            $em->persist($shiftLogArchive);
        }

        $em->flush();
    }
}
