<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * ShiftLogArchiveRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaypointsRepository extends EntityRepository
{

    public function findByArray($wpts){

        return $this->createQueryBuilder('w')
            ->where('w.wpt_id IN (:wpts)')
            ->setParameter('wpts', $wpts)
            ->getQuery()
            ->getArrayResult();
    }

}