<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;


/**
 * ShiftLogArchiveRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaypointsRepository extends EntityRepository
{

    public function findAndOrderByArray($wpts){

        $qb = $this->createQueryBuilder("w");

        return $qb->where('w.wpt_id IN (:wpts)')
            ->setParameter('wpts', $wpts)
            ->getQuery()
            ->getArrayResult();

    }



}